import {
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { join, resolve } from "node:path";

const webRoot = resolve(import.meta.dirname, "..");
const registriesDist = resolve(webRoot, "../../packages/registries/dist");
const publicR = join(webRoot, "public/r");
const registryDataPath = join(webRoot, "src/lib/registry-data.ts");

// Step 1: Clean public/r/
if (existsSync(publicR)) {
  rmSync(publicR, { recursive: true });
}
mkdirSync(publicR, { recursive: true });

// Step 2: Copy dist/* → public/r/
if (!existsSync(registriesDist)) {
  console.error(
    "Registry dist not found. Run `pnpm --filter @repo/registries build` first."
  );
  process.exit(1);
}
cpSync(registriesDist, publicR, { recursive: true });
console.log("Copied registry dist → public/r/");

// Step 3: Generate registry-data.ts from index.json
const indexPath = join(publicR, "index.json");
if (!existsSync(indexPath)) {
  console.error(
    "Missing public/r/index.json — registry build may have failed."
  );
  process.exit(1);
}

const index = JSON.parse(readFileSync(indexPath, "utf-8"));

const registriesLiteral = JSON.stringify(index.registries, null, 2);

const output = `// Auto-generated by apps/web/scripts/prebuild.mts — do not edit
export const registries = ${registriesLiteral} as const;

export type RegistryName = (typeof registries)[number]["name"];
`;

writeFileSync(registryDataPath, output);
console.log("Generated src/lib/registry-data.ts");
